### ISSUE TITLE
Questions about loading and saving jsons in new version of RDR2.

### ISSUE THREAD

**Issue by ZhaojunCP** [BAAI-Agents/Cradle#33]
Thank you for your work! Why doesn't the latest version of RDR2 include operations to load and save files like memory.json and skill_lib.json?

**Comment by DVampire** [comment]
Previously, the process of saving checkpoints involved too many and too complex files. Now, we have achieved saving all necessary information through memory storage. Due to time constraints, the current code is an incomplete version. We will integrate the remaining code and conduct subsequent tests as soon as possible. Thank you for your patience.

**Comment by ZhaojunCP** [comment]
Thanks.
