### ISSUE TITLE
Why generate many specific Skills for each scenario rather than using basic keyboard and mouse-related Skills?

### ISSUE THREAD

**Issue by duoyw** [BAAI-Agents/Cradle#73]
The greatest benefit of vision-based work is that it does not require additional support for each application. However, it seems that you have violated this basic principle in your code.

For example, in RDR2, you have encapsulated many specific APIs for different scenarios.

<img width="1316" alt="image" src="https://github.com/user-attachments/assets/2ab3dd1a-a8a3-41e5-8bf7-8373057dedc5">

In reality, you should only be using some basic APIs such as io_env.key_press(xx).

Otherwise, it will still require additional support for each scenario of each application. Additionally, for some game-specific basic knowledge, such as aiming, you should provide documentation to the large model instead of providing APIs.

Please provide an explanation for this.

**Comment by WeihaoTan** [comment]
Thanks for reaching out. As we described in the paper, these skills are used in open-ended mission in Chapter II. And we only use the minimal set of them rather than all the skills. Some skills there are used for testing and debugging. 

In the main storyline missions, we let the agent generate skills according to the in-game guidance from scratch. However, since we do not let the agent complete the whole Chapter I, for the open-ended tasks in Chapter II, we have to provide some basic skills for the agent to complete the task since it skips the skill generation process in Chapter I, e.g., the agent does not know pressing e to mount the horse, which was told in Chapter I.

**Comment by duoyw** [comment]
However, there are some skills that are system guidance-independent. For instance, purchasing items should be an operation that can be directly clicked on the interface. Could it be that large models cannot even infer this?

<img width="973" alt="image" src="https://github.com/user-attachments/assets/aa8d53c2-0042-421e-8e3d-e9ce1c7cbee4">

Additionally, as I mentioned, some of the skipped system guidance should be provided to the model in the form of knowledge documents, rather than generating APIs. Currently, it seems that the completion of the vast majority of tasks relies on very specific prompts and carefully constructed APIs. This might be a far cry from the ideal form.

**Comment by WeihaoTan** [comment]
As mentioned in the previous reply, the open-ended task skips skill skill-generation process. So we provide the necessary skills to pretend that the agent has generated all the skills needed in the past experiences. Add the skipped information in the prompt as prior knowledge would be another solution, but it would result in a much longer context,  which may greatly influence GPT-4o's performance, especially the instruction following ability. For the main storyline, we let the agent generate skills according to the in-game guidance.

For purchasing, I agreed that a more decent operation would be directly clicked on the interface. But as we mentioned in the paper, current model like GPT-4o struggles with outputting correct pixel-level positions and moving mouse to the target places. Using keyboard would be a more stable way for this task. 

I can totally understand the disappointment you feel, which is what we have been feeling during the whole process of development. That is why our title is "towards" general computer control rather than achieving it. We are actually far from it. We also provide a detailed discussion of the limitations in the appendix of the paper.  This project served as a preliminary attempt towards GCC. I would be happy to see if this project can attract more people to study in this domain and build more powerful agents.
